projet2uqac/Models/ErrorViewModel.cs
namespace projet2uqac.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

projet2uqac/Models/Key.cs
using System.Security.Cryptography;

namespace projet2uqac.Models
{
    public class Key
    {
        public Key(int id, string name, RSAParameters value, bool isPrivate)
        {
            this.id = id;
            this.name = name;
            this.value = value;
            this.isPrivate = isPrivate;
        }
        public int id { get; set; }

        public string? name { get; set; }

        public RSAParameters value { get; set; }

        public bool isPrivate { get; set; }
    }
}

projet2uqac/Controllers/DecryptController.cs
using Microsoft.AspNetCore.Mvc;
using projet2uqac.Models;
using projet2uqac.Services;
using System.Diagnostics;

namespace projet2uqac.Controllers
{
    public class DecryptController : Controller
    {
        private readonly ILogger<DecryptController> _logger;
        //services
        IKeyManagementService _keyService;
        ICryptoOperationServices _cryptoService;
        public DecryptController(ILogger<DecryptController> logger, IKeyManagementService keyService, ICryptoOperationServices cryptoService)
        {
            _logger = logger;
            _keyService = keyService;
            _cryptoService = cryptoService;
        }

        public IActionResult Index()
        {
            return View(_keyService.GetKeys());
        }

        public IActionResult Result()
        {
            int keyID = Convert.ToInt32(HttpContext.Request.Form["keyId"]);
            string message = HttpContext.Request.Form["message"];

            string messageResult = "";

            Key key = _keyService.GetKeyById(keyID);
            try
            {
                if ((key.isPrivate))
                {
                    messageResult = "VOICI TON TEXTE : " + _cryptoService.DecryptMessage(message, key);
                }
                else
                {
                    messageResult = "**Je crois que tu as mal compris la théorie... retourne la voir ;) **";
                }
            }
            catch (Exception ex)
            {
                messageResult = "erreur lors de l'importation vérifie que tout est bon...";
            }

            return View((object)messageResult);
        }
    }
}

projet2uqac/Controllers/EncryptController.cs
using Microsoft.AspNetCore.Mvc;
using projet2uqac.Models;
using projet2uqac.Services;
using System.Diagnostics;

namespace projet2uqac.Controllers
{
    public class EncryptController : Controller
    {
        private readonly ILogger<EncryptController> _logger;
        //services
        IKeyManagementService _keyService;
        ICryptoOperationServices _cryptoService;
        public EncryptController(ILogger<EncryptController> logger, IKeyManagementService keyService, ICryptoOperationServices cryptoService)
        {
            _logger = logger;
            _keyService = keyService;
            _cryptoService = cryptoService;
        }

        public IActionResult Index()
        {
            return View(_keyService.GetKeys());
        }

        public IActionResult Result()
        {
            int keyID = Convert.ToInt32(HttpContext.Request.Form["keyId"]);
            string message = HttpContext.Request.Form["message"];
            string messageResult = "";

            Key key = _keyService.GetKeyById(keyID);

            if ((!key.isPrivate))
            {
                messageResult = "VOICI TON TEXTE : " + _cryptoService.EncryptMessage(message, key);
            }
            else
            {
                messageResult = "**Je crois que tu as mal compris la théorie... retourne la voir ;) **";
            }

            return View((object)messageResult);
        }
    }
}

projet2uqac/Controllers/HomeController.cs
using projet2uqac.Services;
using Microsoft.AspNetCore.Mvc;
using projet2uqac.Models;
using System.Diagnostics;

namespace projet2uqac.Controllers
{
    public class HomeController : Controller
    {
        //services
        IKeyManagementService _keyService;
        IConfiguration _config;

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IKeyManagementService keyService, IConfiguration config)
        {
            _logger = logger;
            _keyService = keyService;
            _config = config;
        }

        public IActionResult Index()
        {
            return View(_keyService.GetKeys());
        }

        [HttpGet]
        public IActionResult GenerateKey()
        {
            string name = "MY PERSONAL KEY";
            _keyService.GenereateMyKeys(name);

            return RedirectToAction("index");
        }

        [HttpGet]   
        public IActionResult Export(int id)
        {
            string res = _keyService.exportKey(id);
            return View((object)res);
        }

        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ImportKey()
        {
            string name = HttpContext.Request.Form["name"];
            string value = HttpContext.Request.Form["key"];
            try
            {
               _keyService.ImportKey(value, name);
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("error", new {message = "La clé que tu essaie d'importer ne semble pas fonctionner" } );
            }

        }

        [HttpGet]
        public IActionResult Error(string message)
        {
            string res = message;
            return View((object)res);
        }
    }
}

projet2uqac/Views/Decrypt/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Key>

<div class="container mt-5">
    <h1>Formulaire de décryption de messages</h1>
    <form asp-action="Result" method="post">
        <div class="form-group">
            <label for="selectElement">Sélectionnez une clé afin de décrypter :</label>
            <select class="form-control" id="selectElement" name="KeyId">
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <option value="@Model[i].id">@Model[i].name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="textareaElement">Entrez le message encrypté :</label>
            <textarea class="form-control" id="textareaElement" rows="4" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Importer</button>
    </form>
</div>

projet2uqac/Views/Decrypt/Result.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model string;
<div class="container mt-5">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4"> <--br>Voici votre clé : </h1>
            <p class="lead">@Model</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg" href="#" role="button" onclick="window.location.href = '@Url.Action("Index","Home")';">Retour</a>
        </div>
    </div>
</div>

projet2uqac/Views/Encrypt/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Key>

<div class="container mt-5">
    <h1>Formulaire d'encryption de messages'</h1>
    <form asp-action="Result" method="post">
        <div class="form-group">
            <label for="selectElement">Sélectionnez une clé afin d'encrypter' :</label>
            <select class="form-control" id="selectElement" name="KeyId">
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <option value="@Model[i].id">@Model[i].name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="textareaElement">Entrez un message à encrypter :</label>
            <textarea class="form-control" id="textareaElement" rows="4" name="message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Importer</button>
    </form>
</div>

projet2uqac/Views/Encrypt/Result.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model string;
<div class="container mt-5">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Voici votre clé : </h1>
            <p class="lead">@Model</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg" href="#" role="button" onclick="window.location.href = '@Url.Action("Index","Home")';">Retour</a>
        </div>
    </div>
</div>
etourner</button>

projet2uqac/Views/Home/Export.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model string;
<div class="container mt-5">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Voici votre clé : </h1>
            <p class="lead">@Model</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg" href="#" role="button" onclick="window.location.href = '@Url.Action("Index","Home")';">Retour</a>
        </div>
    </div>
</div>

projet2uqac/Views/Home/Import.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container mt-5">
    <h1>Formulaire d'importation de clé</h1>
    <form asp-action="ImportKey" method="post">
        <div class="form-group">
            <label for="textareaElement">Entrez le code de la clé</label>
            <textarea class="form-control" id="textareaElement" rows="4" name="key"></textarea>
            <label for="name">nom de la clé</label>
            <input type="text" id="name" name="name" />
        </div>
        <button type="submit" class="btn btn-primary">Importer</button>
    </form>
</div>

projet2uqac/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<projet2uqac.Models.Key>;


<button type="submit" class="btn btn-primary btn-lg" onclick="window.location.href = '@Url.Action("GenerateKey","Home")';" display="inline" style="padding-right: 30px;">Generer mes clées</button>
<button onclick="window.location.href = '@Url.Action("Import","Home")';" class="btn btn-primary btn-lg" display="inline">Importer une clé</button>
<div class="container">
    <h1>Mes clés</h1>
    <div class="row">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <div class="col-md-4">
                <div class="card">
                    <img src="https://t3.ftcdn.net/jpg/02/51/74/82/360_F_251748220_A2cP6VJ19IoXXjWCHL9KY39peKHick1c.jpg" class="card-img-top" alt="Article 1">
                    <div class="card-body">
                        <h5 class="card-title">@Model[i].name</h5>
                        <a href="#" class="btn btn-primary" onclick="window.location.href = '@Url.Action("Export","Home",new{id=Model[i].id})';">Exporter</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

projet2uqac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projet2uqac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projet2uqac.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="/css/logo.png" width="70" height="70" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Decrypt" asp-action="Index">Decrypt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Encrypt" asp-action="Index">Encrypt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - projet2uqac - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>